services:
  mybddapp:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: samir
    ports:
      - "3306:3306"
    volumes:
      - bdd-data:/var/lib/mysql

  mygoapp:
    build:
      context: backend-go
    image: mygoapp
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mybddapp
      
  myangularapp:
    build:
      context: frontend-angular
    image: myangularapp
    restart: always
    ports:
      - "80:80"
      - "4200:4200"
    depends_on:
      - mygoapp
    
  myjenkinsapp:
    image: jenkins/jenkins
    restart: always
    ports: 
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  bdd-data:
  jenkins-data: